version: "2.3"

services:
  generator:
    image: visualroad/core:latest
    working_dir: /app
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - DISPLAY=$DISPLAY
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib/nvidia:/usr/lib/nvidia
    entrypoint: python3 /home/ue4/visualroad/generator.py

  driver:
    image: visualroad/core:latest
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: python3 /home/ue4/visualroad/driver.py

  verifier:
    image: visualroad/core:latest
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: python3 /home/ue4/visualroad/verifier.py

